#ifndef _QZKERNEL_EPUBKIT_EPUBLIB_EXPORT_QZEPUBRETURNCODE_H
#define _QZKERNEL_EPUBKIT_EPUBLIB_EXPORT_QZEPUBRETURNCODE_H

#include "QZKernelReturnCode.h"

#define QZR_EPUBLIB_OPENFILE_FAIL			QZR_EPUBLIB_BASEVALUE			// 打开文件失败
#define QZR_EPUBLIB_BOOK_OPFPATH_ERROR		(QZR_EPUBLIB_BASEVALUE + 1L)    // OPF路径获取错误
#define QZR_EPUBLIB_BOOK_NCXPATH_ERROR		(QZR_EPUBLIB_BASEVALUE + 2L)    // NCX路径获取错误
#define QZR_EPUBLIB_BOOK_OPFLOAD_ERROR		(QZR_EPUBLIB_BASEVALUE + 3L)    // OPF文件解析错误
#define QZR_EPUBLIB_BOOK_NCXLOAD_ERROR		(QZR_EPUBLIB_BASEVALUE + 4L)    // NCX文件解析错误
#define QZR_EPUBLIB_BOOK_HTMLLOAD_ERROR		(QZR_EPUBLIB_BASEVALUE + 5L)    // HTML文件解析错误


#define QZR_EPUBLIB_CSS_FROMAT_ERROR		(QZR_EPUBLIB_BASEVALUE + 6L)	//	CSS格式错误
#define QZR_EPUBLIB_PAGE_CONF_FROMAT_ERROR	(QZR_EPUBLIB_BASEVALUE + 7L)	//	PAGE配置文件格式错误

#endif //_QZKERNEL_EPUBKIT_EPUBLIB_EXPORT_QZEPUBRETURNCODE_H